/**
 * StreamingStateBuilder - Simple, clear accumulation of streaming chunks
 *
 * Design: Just accumulate data, don't parse or transform
 * - Each chunk type has its own accumulator
 * - Clear separation of concerns
 */

// ==================== Types ====================

export type StreamingState = 'connecting' | 'routing' | 'retrieving' | 'generating' | 'complete' | 'error'

export interface RoutingInfo {
  router: string
  intent?: string
}

export interface RetrievalStage {
  iteration: number
  strategy: 'dense' | 'hybrid'
  chunksRetrieved: number      // Number of chunks retrieved
  uniqueDocuments: number      // Number of unique documents
  topDocuments?: string[]      // Top document IDs (max 3)
}

export interface SourceChunk {
  id: string
  chunk_id?: string
  content: string
  score: number
  document_id?: string
  chunk_index?: number
}

export interface Attachment {
  id: string
  type: string
  filename: string
  content_type?: string
  download_url: string
  expires_at?: string
}

/**
 * Complete message state after processing all chunks
 */
export interface MessageState {
  /** Current streaming state */
  status: StreamingState
  /** Routing information */
  routing: RoutingInfo | null
  /** Retrieval stages */
  retrieval: RetrievalStage[]
  /** Main response content (from 'content' chunks) */
  content: string
  /** Source citations */
  sources: SourceChunk[]
  /** Downloadable artifacts generated by the assistant */
  attachments: Attachment[]
  /** Error message if any */
  error: string | null
  /** Timestamp of last update */
  timestamp: number
}

// ==================== Constants ====================

const INITIAL_STATE: MessageState = {
  status: 'connecting',
  routing: null,
  retrieval: [],
  content: '',
  sources: [],
  attachments: [],
  error: null,
  timestamp: Date.now(),
}

// ==================== StreamingStateBuilder ====================

export class StreamingStateBuilder {
  private state: MessageState = { ...INITIAL_STATE }

  /**
   * Process a single SSE chunk and update state
   */
  processChunk(type: string, data: any): void {
    this.state.timestamp = Date.now()

    switch (type) {
      case 'routing':
        this.processRouting(data)
        break

      case 'retrieval':
        this.processRetrieval(data)
        break

      case 'content':
        this.processContent(data)
        break

      case 'metadata':
        this.processMetadata(data)
        break

      case 'done':
        this.processDone()
        break

      case 'error':
        this.processError(data)
        break

      default:
        console.log(`[StreamingStateBuilder] Unknown chunk type: ${type}`)
    }
  }

  /**
   * Get current immutable state snapshot
   */
  getState(): MessageState {
    return {
      status: this.state.status,
      routing: this.state.routing,
      retrieval: [...this.state.retrieval],
      content: this.state.content,
      sources: [...this.state.sources],
      attachments: [...this.state.attachments],
      error: this.state.error,
      timestamp: this.state.timestamp,
    }
  }

  /**
   * Finalize and get complete state
   */
  finalize(): MessageState {
    return {
      ...this.getState(),
      status: 'complete',
    }
  }

  /**
   * Reset builder for new message
   */
  reset(): void {
    this.state = { ...INITIAL_STATE }
  }

  // ==================== Private Methods ====================

  private processRouting(data: any): void {
    this.state.status = 'routing'

    if (data?.router) {
      this.state.routing = {
        router: data.router,
        intent: data.intent,
      }
    }
  }

  private processRetrieval(data: any): void {
    this.state.status = 'retrieving'

    const iteration = data?.iteration ?? 1
    const strategy = data?.strategy ?? 'hybrid'
    // Support both old (docs_retrieved) and new (chunks_retrieved) field names
    const chunksRetrieved = data?.chunks_retrieved ?? data?.docs_retrieved ?? 0
    const uniqueDocuments = data?.unique_documents ?? 1
    const topDocuments = data?.top_documents ?? []

    this.state.retrieval.push({
      iteration,
      strategy: strategy.toLowerCase() === 'hybrid' ? 'hybrid' : 'dense',
      chunksRetrieved,
      uniqueDocuments,
      topDocuments,
    })
  }

  private processContent(data: any): void {
    this.state.status = 'generating'

    const text = data?.text ?? ''
    if (text) {
      this.state.content += text
    }
  }

  private processMetadata(data: any): void {
    this.state.status = 'generating'

    if (data?.citations) {
      this.state.sources = ensureFlatSources(data.citations) || []
    } else if (data?.sources) {
      this.state.sources = ensureFlatSources(data.sources) || []
    }

    if (data?.attachments) {
      this.state.attachments = data.attachments
    }
  }

  private processDone(): void {
    this.state.status = 'complete'
  }

  private processError(data: any): void {
    this.state.status = 'error'
    this.state.error = data?.error ?? 'Unknown error'
  }
}

/**
 * Normalizes/flattens raw sources (which might be in the grouped or flat format)
 * into a flat list of SourceChunk/CitationSource items.
 */
export function ensureFlatSources(rawSources: any[] | undefined): any[] | undefined {
  if (!rawSources) return undefined
  if (rawSources.length === 0) return []

  // Check if it is grouped structure (contains 'chunks')
  const isGrouped = rawSources.some(s => s && s.hasOwnProperty('chunks'))
  if (!isGrouped) {
    return rawSources.map((citation: any, idx: number) => {
      const docTitle = citation.filename || citation.source || citation.title || 'Tài liệu'
      const textVal = citation.text || citation.content || citation.snippet || ''
      const chunkId = citation.chunk_id || citation.id || `chunk-${idx}`
      return {
        id: chunkId,
        chunk_id: chunkId,
        source: docTitle,
        title: docTitle,
        snippet: textVal,
        content: textVal,
        content_length: textVal.length,
        page_number: citation.page_number ?? citation.page,
        score: citation.score ?? citation.confidence,
        grounding_score: citation.grounding_score ?? citation.score ?? citation.confidence,
        document_id: citation.document_id ?? citation.metadata?.document_id,
        chunk_index: citation.chunk_index ?? citation.metadata?.chunk_index ?? idx,
        page: citation.page_number ?? citation.page
      }
    })
  }

  return rawSources.flatMap((doc: any, docIdx: number) => {
    const docTitle = doc.filename || doc.title || 'Tài liệu'
    const docId = doc.document_id || `doc-${docIdx}`

    return (doc.chunks || []).map((chunk: any, chunkIdx: number) => {
      const id = chunk.chunk_id || chunk.id || `${docId}-chunk-${chunkIdx}`
      return {
        id,
        chunk_id: id,
        source: docTitle,
        title: docTitle,
        snippet: chunk.snippet || chunk.content || '',
        content: chunk.content || chunk.snippet || '',
        content_length: chunk.content ? chunk.content.length : (chunk.snippet ? chunk.snippet.length : 0),
        page_number: chunk.page,
        score: chunk.score,
        grounding_score: chunk.grounding_score ?? chunk.score,
        document_id: docId,
        chunk_index: chunk.chunk_index ?? chunkIdx,
        page: chunk.page
      }
    })
  })
}

// ==================== Factory Function ====================

export function createStreamingStateBuilder(): StreamingStateBuilder {
  return new StreamingStateBuilder()
}
