"""Application constants."""

# HTTP Status
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_SERVER_ERROR = 500

# Document Status
DOC_STATUS_UPLOADING = "uploading"
DOC_STATUS_PROCESSING = "processing"
DOC_STATUS_COMPLETED = "completed"
DOC_STATUS_FAILED = "failed"

# Message Role
ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
ROLE_SYSTEM = "system"

# User Role
USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"

# Pagination
DEFAULT_LIMIT = 100
DEFAULT_OFFSET = 0
DEFAULT_CONVERSATION_LIMIT = 50

# LLM Defaults
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 2048
DEFAULT_LLM_TIMEOUT = 60.0

# Processing
DEFAULT_PROCESSING_TIMEOUT = 600
STREAM_CHUNK_SIZE = 10

# RAG
MAX_CONTEXT_TOKENS = 4096
MIN_CONTEXT_LENGTH = 200

# Error Messages
ERR_DOC_NOT_FOUND = "Document not found"
ERR_CONVERSATION_NOT_FOUND = "Conversation not found"
ERR_PROCESSING_FAILED = "Processing failed"
ERR_NO_CONTENT = "No text content after cleaning"
ERR_NO_CHUNKS = "No chunks created"
ERR_EXTRACTION_FAILED = "Extraction failed"

__all__ = [
    "HTTP_OK",
    "HTTP_CREATED",
    "HTTP_BAD_REQUEST",
    "HTTP_UNAUTHORIZED",
    "HTTP_FORBIDDEN",
    "HTTP_NOT_FOUND",
    "HTTP_UNPROCESSABLE_ENTITY",
    "HTTP_INTERNAL_SERVER_ERROR",
    "DOC_STATUS_UPLOADING",
    "DOC_STATUS_PROCESSING",
    "DOC_STATUS_COMPLETED",
    "DOC_STATUS_FAILED",
    "ROLE_USER",
    "ROLE_ASSISTANT",
    "ROLE_SYSTEM",
    "USER_ROLE_USER",
    "USER_ROLE_ADMIN",
    "DEFAULT_LIMIT",
    "DEFAULT_OFFSET",
    "DEFAULT_CONVERSATION_LIMIT",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_LLM_TIMEOUT",
    "DEFAULT_PROCESSING_TIMEOUT",
    "STREAM_CHUNK_SIZE",
    "MAX_CONTEXT_TOKENS",
    "MIN_CONTEXT_LENGTH",
    "ERR_DOC_NOT_FOUND",
    "ERR_CONVERSATION_NOT_FOUND",
    "ERR_PROCESSING_FAILED",
    "ERR_NO_CONTENT",
    "ERR_NO_CHUNKS",
    "ERR_EXTRACTION_FAILED",
]
