"""Port: LLM provider contract.

Application core depends on this ABC, NOT on specific LLM implementations.
Allows swapping GLM ↔ Claude ↔ GPT-4 ↔ Gemini without changing core logic.

To use a different LLM, implement LLMPort and wire it in server/main.py.
"""
from abc import ABC, abstractmethod
from typing import AsyncIterator, Any


class LLMPort(ABC):
    """Port: what the application needs from any LLM provider.

    This is the dependency inversion point for all LLM calls.
    Application code should depend on this interface, not on
    GLMClient, anthropic.Anthropic, or openai.OpenAI directly.

    Example:
        >>> class MyLLM(LLMPort):
        ...     async def generate(self, messages, **kwargs) -> str:
        ...         return "response"
        ...     async def stream(self, messages, **kwargs):
        ...         yield "token"
        ...     async def health_check(self) -> bool:
        ...         return True
    """

    @abstractmethod
    async def generate(
        self,
        messages: list[dict[str, str]],
        temperature: float = 0.7,
        max_tokens: int = 2000,
        **kwargs: Any,
    ) -> str:
        """Generate a complete text response.

        Args:
            messages: Conversation history as list of {role, content} dicts
            temperature: Sampling temperature (0.0 = deterministic, 1.0 = creative)
            max_tokens: Maximum tokens to generate

        Returns:
            Generated text content as a string
        """
        ...

    @abstractmethod
    async def stream(
        self,
        messages: list[dict[str, str]],
        temperature: float = 0.7,
        max_tokens: int = 2000,
        **kwargs: Any,
    ) -> AsyncIterator[str]:
        """Stream text generation token by token.

        Args:
            messages: Conversation history
            temperature: Sampling temperature
            max_tokens: Maximum tokens to generate

        Yields:
            Text chunks as they are generated by the LLM
        """
        ...

    @abstractmethod
    async def health_check(self) -> bool:
        """Check if LLM provider is reachable and operational.

        Returns:
            True if provider is healthy, False otherwise
        """
        ...
